// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlufvydhpqvypmufwdee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsdWZ2eWRocHF2eXBtdWZ3ZGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjAyNzAsImV4cCI6MjA2NzE5NjI3MH0.UqviAhXOc-86Di5A9w4_bU_0y5-Hmx05oKvSvt5Yxb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});